spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fornecedor
    username: postgres
    password: postgres
    platform: postgres
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
    ddl-auto: create
    use_jdbc_metadata_defaults : false
